name: Deploy to Azure Static Web Apps - test

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_BUSH_0C6C7EB10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub
          action: "upload"
          #### REPLACE 'YOUR_APP_LOCATION' AND 'YOUR_OUTPUT_LOCATION' BELOW ####
          app_location: "/" # The location of your app code
          output_location: "dist" # The location of your build output directory
